In [1]:
import socket
import requests
import requests_oauthlib
import json
import pickle
import numpy as np
import pandas as pd

# Replace the values below with yours
ACCESS_TOKEN = ''
ACCESS_SECRET = ''
CONSUMER_KEY = ''
CONSUMER_SECRET = ''
my_auth = requests_oauthlib.OAuth1(CONSUMER_KEY, CONSUMER_SECRET,ACCESS_TOKEN, ACCESS_SECRET)

def top_tweets():
    dict_woeid={23424908:"Nigeria",23424977:"United States",23424856:"Japan",23424975:"United Kingdom",23424938:"Saudi Arabia",23424969:"Turkey",23424768:"Brazil",23424848:"India",23424900:"Mexico",23424950:"Spain",23424819:"France"}
    data={}
    for key in dict_woeid.keys():
        url = 'https://api.twitter.com/1.1/trends/place.json?id='+str(key)
        response = requests.get(url, auth=my_auth, stream=True)
        trend=response.json()[0]["trends"]
        tweets=[] 
        tweets.append("Hashtag : Tweet Volume")
        tweets_top=[]
        for x in trend:
            if x['tweet_volume']!=None:
                tweets_top.append((x['name'],x['tweet_volume']))
        tweets_top.sort(key= lambda x:x[1],reverse=True)
        tweets_top=tweets_top[:5]
        for x in tweets_top:
            tweets.append(x[0]+" : "+str(x[1]))
        data["Country: "+dict_woeid[key]]=tweets
    return pd.DataFrame(data)

In [2]:
top_tweets()

,Country: Nigeria,Country: United States,Country: Japan,Country: United Kingdom,Country: Saudi Arabia,Country: Turkey,Country: Brazil,Country: India,Country: Mexico,Country: Spain,Country: France
0,Hashtag : Tweet Volume,Hashtag : Tweet Volume,Hashtag : Tweet Volume,Hashtag : Tweet Volume,Hashtag : Tweet Volume,Hashtag : Tweet Volume,Hashtag : Tweet Volume,Hashtag : Tweet Volume,Hashtag : Tweet Volume,Hashtag : Tweet Volume,Hashtag : Tweet Volume
1,Netherlands : 325744,#60Minutes : 71686,ワールドトリガー : 95547,patriots : 227858,#ARMYIndependenceDay : 664357,Brunson : 136900,#ARMYIndependenceDay : 664357,Saudi Arabia : 232941,#BTSKOREASPRIDE : 167492,#ARMYIndependenceDay : 664357,Ninho : 205229
2,Drake : 310328,#KCvsNE : 70964,ジャンプSQ : 73927,Ariana Grande : 184218,#كلمه_لاعداء_مملكتنا_السعوديه : 289771,#AtayaUzananEliKırarız : 60380,Patriots : 227858,#MeToo : 230485,#GoPats : 61081,#OTDirecto14OCT : 141891,#BONJOURBTS : 196823
3,Jesus : 265682,#MasterChefMx : 58815,SQ移籍 : 67678,#SundayMorning : 99513,#اليوم_العالمي_للعيون : 85038,#pazar : 52309,Pete Davidson : 155930,#விஸ்வாசம்திருவிழாஆரம்பம் : 126042,#MasterChefMx : 58815,Leslie : 118322,Booba : 102021
4,Kanye West : 165817,#90DayFiance : 33682,ワートリ : 50298,portugal : 83273,#عبدالعزيز_جاسم_في_ذمه_الله : 78524,#Kızımİçin : 24771,#NBTSTourSãoPaulo : 127644,We Love Nehha : 82478,Houston : 51153,Chiefs : 111807,portugal : 83273
5,Church : 149598,Gordon : 27816,あんステ : 23914,#KCvsNE : 70964,#شعوري_الليله_بتغريده : 42884,#SensizAsla : 24512,GOAT : 42302,#immoralactsinchurches : 81767,DISNEY SE PINTA DE VIOLETTA : 34243,#GHVIPDBT5 : 91071,nations : 66467